<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateEnfermeriasTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('enfermerias', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('adulto_id');
            $table->foreign('adulto_id')->references('id')->on('adultos_mayores');  
            $table->string('pregunta1',100)->nullable();
            $table->string('pregunta2',100)->nullable();
            $table->string('pregunta3',100)->nullable();
            $table->string('pregunta4',100)->nullable();
            $table->string('pregunta5',100)->nullable();
            $table->string('pregunta6',100)->nullable();
            $table->string('pregunta7',100)->nullable();
            $table->string('pregunta8',100)->nullable();
            $table->string('pregunta9',100)->nullable();
            $table->string('pregunta10',100)->nullable();
            $table->string('pregunta11',100)->nullable();
            $table->string('pregunta12',100)->nullable();
            $table->string('pregunta13',100)->nullable();
            $table->string('pregunta14',100)->nullable();
            $table->string('pregunta15',100)->nullable();
            $table->string('pregunta16',100)->nullable();
            $table->string('pregunta17',100)->nullable();
            $table->string('pregunta18',100)->nullable();
            $table->string('pregunta19',100)->nullable();
            $table->string('pregunta20',100)->nullable();
            $table->string('pregunta21',100)->nullable();
            $table->string('pregunta22',100)->nullable();
            $table->string('pregunta23',100)->nullable();
            $table->string('pregunta24',100)->nullable();
            $table->string('pregunta25',100)->nullable();
            $table->string('pregunta26',100)->nullable();
            $table->string('pregunta27',100)->nullable();
            $table->string('pregunta28',100)->nullable();
            $table->string('pregunta29',100)->nullable();
            $table->string('pregunta30',100)->nullable();
            $table->string('pregunta31',100)->nullable();
            $table->string('pregunta32',100)->nullable();
            $table->string('pregunta33',100)->nullable();
            $table->string('pregunta34',100)->nullable();
            $table->string('pregunta35',100)->nullable();
            $table->string('pregunta36',100)->nullable();
            $table->string('pregunta37',100)->nullable();
            $table->string('pregunta38',100)->nullable();
            $table->string('pregunta39',100)->nullable();
            $table->string('pregunta40',100)->nullable();
            $table->string('pregunta41',100)->nullable();
            $table->string('pregunta42',100)->nullable();
            $table->string('pregunta43',100)->nullable();
            $table->string('pregunta44',100)->nullable();
            $table->string('pregunta45',100)->nullable();
            $table->string('pregunta46',100)->nullable();
            $table->string('pregunta47',100)->nullable();
            $table->string('pregunta48',100)->nullable();
            $table->string('pregunta49',100)->nullable();
            $table->string('pregunta50',100)->nullable();
            $table->string('pregunta51',100)->nullable();
            $table->string('pregunta52',100)->nullable();
            $table->string('pregunta53',100)->nullable();
            $table->string('pregunta54',100)->nullable();
            $table->string('pregunta55',100)->nullable();
            $table->string('pregunta56',100)->nullable();
            $table->string('pregunta57',100)->nullable();
            $table->string('pregunta58',100)->nullable();
            $table->string('pregunta59',100)->nullable();
            $table->string('pregunta60',100)->nullable();
            $table->string('pregunta61',100)->nullable();
            $table->string('pregunta62',100)->nullable();
            $table->string('pregunta63',100)->nullable();
            $table->string('pregunta64',100)->nullable();
            $table->string('pregunta65',100)->nullable();
            $table->string('pregunta66',100)->nullable();
            $table->string('pregunta67',100)->nullable();
            $table->string('pregunta68',100)->nullable();
            $table->string('pregunta69',100)->nullable();
            $table->string('pregunta70',100)->nullable();
            $table->string('pregunta71',100)->nullable();
            $table->string('pregunta72',100)->nullable();
            $table->string('pregunta73',100)->nullable();
            $table->string('pregunta74',100)->nullable();
            $table->string('pregunta75',100)->nullable();
            $table->string('pregunta76',100)->nullable();
            $table->string('pregunta77',100)->nullable();
            $table->string('pregunta78',100)->nullable();
            $table->string('pregunta79',100)->nullable();
            $table->string('pregunta80',100)->nullable();
            $table->string('pregunta81',100)->nullable();
            $table->string('pregunta82',100)->nullable();
            $table->string('pregunta83',100)->nullable();
            $table->string('pregunta84',100)->nullable();
            $table->string('pregunta85',100)->nullable();
            $table->string('pregunta86',100)->nullable();
            $table->string('pregunta87',100)->nullable();
            $table->string('pregunta88',100)->nullable();
            $table->string('pregunta89',100)->nullable();
            $table->string('pregunta90',100)->nullable();
            $table->string('pregunta91',100)->nullable();
            $table->string('pregunta92',100)->nullable();
            $table->string('pregunta93',100)->nullable();
            $table->string('pregunta94',100)->nullable();
            $table->string('pregunta95',100)->nullable();
            $table->string('pregunta96',100)->nullable();
            $table->string('pregunta97',100)->nullable();
            $table->string('pregunta98',100)->nullable();
            $table->string('pregunta99',100)->nullable();
            $table->string('pregunta100',100)->nullable();
            $table->string('pregunta101',100)->nullable();
            $table->string('pregunta102',100)->nullable();
            $table->string('pregunta103',100)->nullable();
            $table->string('pregunta104',100)->nullable();
            $table->string('pregunta105',100)->nullable();
            $table->string('pregunta106',100)->nullable();
            $table->string('pregunta107',100)->nullable();
            $table->string('pregunta108',100)->nullable();
            $table->string('pregunta109',100)->nullable();
            $table->string('pregunta110',100)->nullable();
            $table->string('pregunta111',100)->nullable();
            $table->string('pregunta112',100)->nullable();
            $table->string('pregunta113',100)->nullable();
            $table->string('pregunta114',100)->nullable();
            $table->string('pregunta115',100)->nullable();
            $table->string('pregunta116',100)->nullable();
            $table->string('pregunta117',100)->nullable();
            $table->string('pregunta118',100)->nullable();
            $table->string('pregunta119',100)->nullable();
            $table->string('pregunta120',100)->nullable();
            $table->string('pregunta121',100)->nullable();
            $table->string('pregunta122',100)->nullable();
            $table->string('pregunta123',100)->nullable();
            $table->string('pregunta124',100)->nullable();
            $table->string('pregunta125',100)->nullable();
            $table->string('pregunta126',100)->nullable();
            $table->string('pregunta127',100)->nullable();
            $table->string('pregunta128',100)->nullable();
            $table->string('pregunta129',100)->nullable();
            $table->string('pregunta130',100)->nullable();
            $table->string('pregunta131',100)->nullable();
            $table->string('pregunta132',100)->nullable();
            $table->string('pregunta133',100)->nullable();
            $table->string('pregunta134',100)->nullable();
            $table->string('pregunta135',100)->nullable();
            $table->string('pregunta136',100)->nullable();
            $table->string('pregunta137',100)->nullable();
            $table->string('pregunta138',100)->nullable();
            $table->string('pregunta139',100)->nullable();
            $table->string('pregunta140',100)->nullable();
            $table->string('pregunta141',100)->nullable();
            $table->string('pregunta142',100)->nullable();
            $table->string('pregunta143',100)->nullable();
            $table->string('pregunta144',100)->nullable();
            $table->string('pregunta145',100)->nullable();
            $table->string('pregunta146',100)->nullable();
            $table->string('pregunta147',100)->nullable();
            $table->string('pregunta148',100)->nullable();
            $table->string('pregunta149',100)->nullable();
            $table->string('pregunta150',100)->nullable();
            $table->string('pregunta151',100)->nullable();
            $table->string('pregunta152',100)->nullable();
            $table->string('pregunta153',100)->nullable();
            $table->string('pregunta154',100)->nullable();
            $table->string('pregunta155',100)->nullable();
            $table->string('pregunta156',100)->nullable();
            $table->string('pregunta157',100)->nullable();
            $table->string('pregunta158',100)->nullable();
            $table->string('pregunta159',100)->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('enfermerias');
    }
}
